spring:
  application:
    name: AccountFlow
    description: "Приложение для работы со счетами пользователей"
    version: 1.0
  datasource:
    url: jdbc:postgresql://localhost:5432/account_flow
    username: pavel
    password: pavel
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
jwt:
  secret-key: 73357638792F423F4528482B4D6251655468576D5A7133743677397A24432646
  expiration-time: 900000
redis:
  ttl: 15
balance:
  fixed-rate: 30000
  initial-delay: 30000
  increase-multiplier: 1.1
  max-multiplier: 2.07
scheduling:
  enabled: true
