###save
POST http://localhost:8080/emails
Accept: application/json
Content-Type: application/json
USER_ID: 4

{
  "email": "maria3.personal@example.com"
}

###update
PATCH http://localhost:8080/emails/19
Accept: application/json
Content-Type: application/json
USER_ID: 4

{
  "email": "maria7.personal@example.com"
}

###delete
DELETE http://localhost:8080/emails/19
Accept: application/json
Content-Type: application/json
USER_ID: 4
