###save
POST http://localhost:8080/phones/1
Accept: application/json
Content-Type: application/json

{
  "phone": "79297865416"
}

###update
PATCH http://localhost:8080/phones/43
Accept: application/json
Content-Type: application/json

{
  "phone": "79297865421"
}

###delete
DELETE http://localhost:8080/phones/43
Accept: application/json
Content-Type: application/json
